import { putJob, getJob, getJobs, deleteJob, clearJobs, loadSettings, saveSettings, getApiKey, apiKeyIsRemembered, saveApiKey, forgetApiKey } from "./db.js";
import { DEFAULT_SETTINGS, parseWorkbook, auditBatch, downloadWorkbook } from "./audit.js";

const $ = id => document.getElementById(id);
const els = Object.fromEntries(["file-input","drop-zone","file-card","file-name","file-meta","remove-file","validation","start-audit","page-title","key-state","run-name","pause-run","download-result","progress-label","progress-percent","progress-bar","metric-leads","metric-batch","metric-completed","metric-status","metric-input-tokens","metric-cached-tokens","metric-output-tokens","live-log","clear-console","history-list","clear-history","api-key","remember-key","toggle-key","save-key","forget-key","key-message","batch-size","model","system-prompt","save-settings","reset-settings","settings-message","toast","mobile-menu"].map(id=>[id,$(id)]));
let parsedFile=null, currentJob=null, controller=null, settings=loadSettings(DEFAULT_SETTINGS), displayLogs=true;
const titles={new:"New audit",console:"Run console",history:"History",settings:"Settings"};

function showView(name){ document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===`view-${name}`)); document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===name)); els["page-title"].textContent=titles[name]; document.querySelector(".shell").classList.remove("menu-open"); if(name==="history") renderHistory(); }
function toast(message){ els.toast.textContent=message; els.toast.classList.add("show"); clearTimeout(toast.timer); toast.timer=setTimeout(()=>els.toast.classList.remove("show"),2600); }
function updateKeyState(){ const ready=Boolean(getApiKey()); els["key-state"].textContent=ready?"API key ready":"API key not set"; els["key-state"].classList.toggle("ready",ready); }
function timeText(iso){ return new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(iso)); }
function addLog(job,message,level="info") { const entry={at:new Date().toISOString(),level,message}; job.logs.push(entry); if(job.logs.length>1200) job.logs=job.logs.slice(-1200); renderLogs(job); }
function renderLogs(job){ if(!displayLogs){ els["live-log"].innerHTML='<div class="empty-state">Log view cleared. New events will reappear.</div>'; return; } const logs=job?.logs||[]; els["live-log"].replaceChildren(); if(!logs.length){els["live-log"].innerHTML='<div class="empty-state">Run activity will appear here.</div>';return;} for(const item of logs){const row=document.createElement("div");row.className=`log-entry ${item.level}`; const t=document.createElement("span"),l=document.createElement("span"),m=document.createElement("span");t.className="time";t.textContent=new Date(item.at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit",second:"2-digit"});l.className="level";l.textContent=item.level.toUpperCase();m.textContent=item.message;row.append(t,l,m);els["live-log"].append(row);} els["live-log"].scrollTop=els["live-log"].scrollHeight; }
function renderProgress(job){ currentJob=job; const total=job.totalLeads||0,done=job.results?.length||0,pct=total?Math.round(done/total*100):0,batches=Math.ceil(total/job.settings.batchSize),usage=job.tokenUsage||{}; els["run-name"].textContent=job.fileName||"No active audit"; els["progress-label"].textContent=job.status==="completed"?"Audit complete":job.status==="running"?`Auditing lead journeys…`:job.status==="paused"?"Audit paused — ready to resume":job.status==="failed"?"Audit stopped — saved work is safe":"Waiting for a file"; els["progress-percent"].textContent=`${pct}%`;els["progress-bar"].style.width=`${pct}%`;els["metric-leads"].textContent=total||"—";els["metric-batch"].textContent=total?`${Math.min(job.nextBatch+1,batches)} / ${batches}`:"—";els["metric-completed"].textContent=total?`${done} / ${total}`:"—";els["metric-status"].textContent=job.status[0].toUpperCase()+job.status.slice(1);els["metric-input-tokens"].textContent=usage.input?usage.input.toLocaleString():"—";els["metric-cached-tokens"].textContent=usage.cached?usage.cached.toLocaleString():"0";els["metric-output-tokens"].textContent=usage.output?usage.output.toLocaleString():"—";els["pause-run"].disabled=!(["running","paused","failed"].includes(job.status));els["pause-run"].textContent=job.status==="running"?"Pause":"Resume";els["download-result"].disabled=job.status!=="completed";renderLogs(job); }

async function handleFile(file){ if(!/\.(xlsx|xls|xlsm)$/i.test(file.name)){toast("Choose an Excel workbook.");return;} els.validation.className="validation";els.validation.textContent="Reading workbook…"; try{const buffer=await file.arrayBuffer();const parsed=parseWorkbook(buffer);parsedFile={...parsed,fileName:file.name,fileSize:file.size};els["file-name"].textContent=file.name;els["file-meta"].textContent=`${(file.size/1048576).toFixed(1)} MB · ${parsed.sheetName} · ${parsed.leads.length.toLocaleString()} leads`;els["file-card"].classList.remove("hidden");els.validation.textContent=`Ready: ${parsed.rowCount.toLocaleString()} history rows grouped into ${parsed.leads.length.toLocaleString()} unique Project + Mobile journeys.`;els["start-audit"].disabled=false;}catch(e){parsedFile=null;els.validation.className="validation error";els.validation.textContent=e.message;els["file-card"].classList.add("hidden");els["start-audit"].disabled=true;} }

async function runJob(job){ const key=getApiKey(); if(!key){showView("settings");toast("Add an OpenAI API key first.");return;} if(!/^sk-[A-Za-z0-9_-]{20,}$/.test(key)){showView("settings");toast("That does not look like an OpenAI API key.");return;} controller=new AbortController();job.status="running";job.error="";job.updatedAt=new Date().toISOString();displayLogs=true;addLog(job,`Run started with batch size ${job.settings.batchSize} and model ${job.settings.model}.`);await putJob(job);renderProgress(job);showView("console"); const totalBatches=Math.ceil(job.leads.length/job.settings.batchSize);
  try{for(let i=job.nextBatch;i<totalBatches;i++){const start=i*job.settings.batchSize,batch=job.leads.slice(start,start+job.settings.batchSize);addLog(job,`Sending batch ${i+1}/${totalBatches} (${batch.length} leads).`);renderProgress(job);const rows=await auditBatch(key,job.settings,batch,controller.signal,(m,l)=>addLog(job,m,l),usage=>{job.tokenUsage=job.tokenUsage||{input:0,cached:0,output:0};job.tokenUsage.input+=usage.input;job.tokenUsage.cached+=usage.cached;job.tokenUsage.output+=usage.output;renderProgress(job);});job.results.push(...rows);job.nextBatch=i+1;job.updatedAt=new Date().toISOString();addLog(job,`Batch ${i+1} saved locally. ${job.results.length}/${job.totalLeads} leads complete.`);await putJob(job);renderProgress(job);} job.status="completed";job.updatedAt=new Date().toISOString();addLog(job,"Audit complete. The Excel report is ready to download.","success");await putJob(job);renderProgress(job);toast("Audit complete.");}
  catch(e){if(e.name==="AbortError"){job.status="paused";addLog(job,"Audit paused. Completed batches remain saved on this device.","warn");}else{job.status="failed";job.error=e.message;addLog(job,e.message,"error");}job.updatedAt=new Date().toISOString();await putJob(job);renderProgress(job);}finally{controller=null;}}

async function startNew(){if(!parsedFile)return;const job={id:crypto.randomUUID(),fileName:parsedFile.fileName,sheetName:parsedFile.sheetName,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),status:"queued",totalLeads:parsedFile.leads.length,nextBatch:0,leads:parsedFile.leads,results:[],logs:[],tokenUsage:{input:0,cached:0,output:0},settings:{...settings}};await putJob(job);await runJob(job);}

async function renderHistory(){const jobs=await getJobs();els["history-list"].replaceChildren();if(!jobs.length){els["history-list"].innerHTML='<div class="empty-card">No audits yet.</div>';return;}for(const job of jobs){const card=document.createElement("article");card.className="history-item";const info=document.createElement("div"),title=document.createElement("strong"),status=document.createElement("span"),meta=document.createElement("div"),actions=document.createElement("div");title.textContent=job.fileName;status.className=`status ${job.status}`;status.textContent=job.status;meta.className="history-meta";meta.textContent=`${timeText(job.createdAt)} · ${job.results.length}/${job.totalLeads} leads · ${job.settings.model}`;info.append(title,document.createTextNode(" "),status,meta);actions.className="history-actions";if(job.status==="completed"){const d=document.createElement("button");d.className="primary-button";d.textContent="Download";d.onclick=()=>downloadWorkbook(job);actions.append(d);}else{const r=document.createElement("button");r.className="primary-button";r.textContent="Resume";r.onclick=async()=>runJob(await getJob(job.id));actions.append(r);}const logs=document.createElement("button");logs.className="secondary-button";logs.textContent="View logs";logs.onclick=async()=>{displayLogs=true;renderProgress(await getJob(job.id));showView("console");};const del=document.createElement("button");del.className="text-button";del.textContent="Delete";del.onclick=async()=>{if(confirm("Delete this audit and its local logs?")){await deleteJob(job.id);renderHistory();}};actions.append(logs,del);card.append(info,actions);els["history-list"].append(card);}}

function populateSettings(){settings=loadSettings(DEFAULT_SETTINGS);els["batch-size"].value=settings.batchSize;els.model.value=settings.model;els["system-prompt"].value=settings.systemPrompt;els["api-key"].value=getApiKey();els["remember-key"].checked=apiKeyIsRemembered();updateKeyState();}

document.querySelectorAll(".nav-item").forEach(button=>button.addEventListener("click",()=>showView(button.dataset.view)));
els["mobile-menu"].onclick=()=>document.querySelector(".shell").classList.toggle("menu-open");
els["drop-zone"].onclick=()=>els["file-input"].click(); els["drop-zone"].onkeydown=e=>{if(["Enter"," "].includes(e.key))els["file-input"].click();}; els["file-input"].onchange=e=>handleFile(e.target.files[0]);
for(const event of ["dragenter","dragover"]){els["drop-zone"].addEventListener(event,e=>{e.preventDefault();els["drop-zone"].classList.add("dragover");});}for(const event of ["dragleave","drop"]){els["drop-zone"].addEventListener(event,e=>{e.preventDefault();els["drop-zone"].classList.remove("dragover");});}els["drop-zone"].addEventListener("drop",e=>handleFile(e.dataTransfer.files[0]));
els["remove-file"].onclick=()=>{parsedFile=null;els["file-card"].classList.add("hidden");els.validation.classList.add("hidden");els["file-input"].value="";els["start-audit"].disabled=true;};els["start-audit"].onclick=startNew;
els["pause-run"].onclick=async()=>{if(currentJob?.status==="running")controller?.abort();else if(currentJob)await runJob(await getJob(currentJob.id));};els["download-result"].onclick=()=>currentJob&&downloadWorkbook(currentJob);els["clear-console"].onclick=()=>{displayLogs=false;renderLogs(currentJob);};
els["clear-history"].onclick=async()=>{if(confirm("Delete all locally stored audits, checkpoints and logs?")){await clearJobs();currentJob=null;renderHistory();toast("Local history cleared.");}};
els["toggle-key"].onclick=()=>{const hidden=els["api-key"].type==="password";els["api-key"].type=hidden?"text":"password";els["toggle-key"].textContent=hidden?"Hide":"Show";};
els["save-key"].onclick=()=>{const key=els["api-key"].value.trim();if(!key){els["key-message"].textContent="Enter a key.";return;}saveApiKey(key,els["remember-key"].checked);els["key-message"].textContent=els["remember-key"].checked?"Saved on this device.":"Saved for this browser session.";updateKeyState();};
els["forget-key"].onclick=()=>{forgetApiKey();els["api-key"].value="";els["remember-key"].checked=false;els["key-message"].textContent="Key removed.";updateKeyState();};
els["save-settings"].onclick=()=>{const batch=Number(els["batch-size"].value);if(!Number.isInteger(batch)||batch<1||batch>50){els["settings-message"].textContent="Batch size must be 1–50.";return;}settings={batchSize:batch,model:els.model.value.trim(),systemPrompt:els["system-prompt"].value.trim()};saveSettings(settings);els["settings-message"].textContent="Saved.";};
els["reset-settings"].onclick=()=>{settings={...DEFAULT_SETTINGS};saveSettings(settings);populateSettings();els["settings-message"].textContent="Defaults restored.";};

populateSettings(); renderHistory();
if("serviceWorker" in navigator) navigator.serviceWorker.register("./service-worker.js").catch(()=>{});
